### ISSUE TITLE
History of GENIE

### ISSUE THREAD

**Issue by meerfrau** [derpycode/cgenie#5]
@ian-ross Hi Ian,

I'm interested in the history of the [Grid Enabled Integrated Earth System Model](https://www.ercim.eu/publication/Ercim_News/enw61/price.html). Have you once been the main developer?

**Comment by ian-ross** [comment]
Not me. You want https://github.com/derpycode (https://profiles.ucr.edu/app/home/profile/aridgwel).

**Comment by derpycode** [comment]
Not me either, said the cat.

O wait, yes, it is me ...


> 
> Not me. You want https://github.com/derpycode 
> (https://profiles.ucr.edu/app/home/profile/aridgwel).
> —
> Reply to this email directly, view it on GitHub, or unsubscribe .
> You are receiving this because you are subscribed to this thread.


/andy


# ---
Dr. Andy Ridgwell
# ---
Professor of Earth System Science
Department of Earth & Planetary Sciences
University of California, Riverside
900 University Ave.
Riverside, CA 92521
# ---
***@***.***
https://www.seao2.info/
https://github.com/derpycode
@***@***.***
# ---

**Comment by ian-ross** [comment]
It is, was and always will be you, Dr. Ridgwell.
